//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableReserve.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesExceptionResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableReserve.Exception.MessagesExceptionResource", typeof(MessagesExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You don’t have access to this resource.
        /// </summary>
        public static string ACCESS_DENIED_VALIDATION {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This request needs an access token.
        /// </summary>
        public static string ACCESS_TOKEN_REQUIRED_VALIDATION {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_REQUIRED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email is invalid.
        /// </summary>
        public static string EMAIL_INVALID_VALIDATION {
            get {
                return ResourceManager.GetString("EMAIL_INVALID_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email is required.
        /// </summary>
        public static string EMAIL_REQUIRED_VALIDATION {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid email or password.
        /// </summary>
        public static string LOGIN_INVALID_VALIDATION {
            get {
                return ResourceManager.GetString("LOGIN_INVALID_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name cannot exceed 250 characters.
        /// </summary>
        public static string NAME_MAX_LENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("NAME_MAX_LENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name must be at least 3 characters long.
        /// </summary>
        public static string NAME_MIN_LENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("NAME_MIN_LENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is required.
        /// </summary>
        public static string NAME_REQUIRED_VALIDATION {
            get {
                return ResourceManager.GetString("NAME_REQUIRED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one lowercase letter.
        /// </summary>
        public static string PASSWORD_LOWERCASE_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_LOWERCASE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password cannot exceed 255 characters.
        /// </summary>
        public static string PASSWORD_MAX_LENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_MAX_LENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must be at least 8 characters long.
        /// </summary>
        public static string PASSWORD_MIN_LENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_MIN_LENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one number.
        /// </summary>
        public static string PASSWORD_NUMBER_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_NUMBER_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password is required.
        /// </summary>
        public static string PASSWORD_REQUIRED_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one special character.
        /// </summary>
        public static string PASSWORD_SPECIAL_CHAR_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_SPECIAL_CHAR_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one uppercase letter.
        /// </summary>
        public static string PASSWORD_UPPERCASE_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_UPPERCASE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Refresh token has expired. Please log in again to obtain a new refresh token..
        /// </summary>
        public static string REFRESH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reservation is already cancelled.
        /// </summary>
        public static string RESERVATION_ALREADY_CANCELLED_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_ALREADY_CANCELLED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reservation date must be in the future.
        /// </summary>
        public static string RESERVATION_DATE_FUTURE_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_DATE_FUTURE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reservation date is required.
        /// </summary>
        public static string RESERVATION_DATE_REQUIRED_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_DATE_REQUIRED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duration must be between 20 and 120 minutes, in steps of 20 (20, 40, 60, 80, 100, 120).
        /// </summary>
        public static string RESERVATION_DURATION_INVALID_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_DURATION_INVALID_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number of guests is required.
        /// </summary>
        public static string RESERVATION_GUESTS_REQUIRED_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_GUESTS_REQUIRED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reservation not found.
        /// </summary>
        public static string RESERVATION_NOT_FOUND_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_NOT_FOUND_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reservation must be within the restaurant&apos;s business hours (08:00-23:00).
        /// </summary>
        public static string RESERVATION_OUTSIDE_BUSINESS_HOURS_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_OUTSIDE_BUSINESS_HOURS_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Table is already booked for the requested time.
        /// </summary>
        public static string RESERVATION_TABLE_UNAVAILABLE_VALIDATION {
            get {
                return ResourceManager.GetString("RESERVATION_TABLE_UNAVAILABLE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number of guests exceeds table capacity.
        /// </summary>
        public static string TABLE_CAPACITY_EXCEEDED_VALIDATION {
            get {
                return ResourceManager.GetString("TABLE_CAPACITY_EXCEEDED_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacity must be at least 1.
        /// </summary>
        public static string TABLE_CAPACITY_MIN_VALIDATION {
            get {
                return ResourceManager.GetString("TABLE_CAPACITY_MIN_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Table not found.
        /// </summary>
        public static string TABLE_NOT_FOUND_VALIDATION {
            get {
                return ResourceManager.GetString("TABLE_NOT_FOUND_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status is invalid. Valid values: Available, Reserved, Inactive.
        /// </summary>
        public static string TABLE_STATUS_INVALID_VALIDATION {
            get {
                return ResourceManager.GetString("TABLE_STATUS_INVALID_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Table is not available for reservations.
        /// </summary>
        public static string TABLE_UNAVAILABLE_VALIDATION {
            get {
                return ResourceManager.GetString("TABLE_UNAVAILABLE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Internal error.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
