<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\TableReserve.Communication\TableReserve.Communication.csproj" />
    <ProjectReference Include="..\..\shared\TableReserve.Exception\TableReserve.Exception.csproj" />
    <ProjectReference Include="..\TableReserve.Application\TableReserve.Application.csproj" />
    <ProjectReference Include="..\TableReserve.Infrastructure\TableReserve.Infrastructure.csproj" />
  </ItemGroup>

</Project>
